
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml 
mqtt: !include mqtt.yaml

#frontend:
#  themes: !include_dir_merge_named themes


# PI hardware resources    
sensor: 
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_use_percent
      - type: load_1m
      - type: load_5m  
   
#   qos: 0
   

